import { FC } from 'react';
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '../components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Test Assignment',
	description: 'Generated by create next app'
};

type RootLayoutProps = {
	children: React.ReactNode;
	params: {
		userId: number;
	};
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<main className="main">{children}</main>
			</body>
		</html>
	);
};

export default RootLayout;
